---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  li-pca-app:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/li-pca-app
    init: true
    restart: on-failure
    environment:
      - ECHO_MESSAGE="Hello from li-pca-app!"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: quote_txt
        target: quote.txt

  li-pca-app-version:
    # Run the container to collect version information
    image: cisagov/li-pca-app
    init: true
    restart: on-failure
    command: --version
